### ISSUE TITLE
Cool! :-)

### ISSUE THREAD

**Issue by jmandel** [fhirbase/fhir.clj#1]
Just reading through the code -- this looks very nice!

BTW you might consider this [algo.generic fmap](https://clojure.github.io/algo.generic/clojure.algo.generic.functor-api.html#clojure.algo.generic.functor/fmap) over the following:

* https://github.com/fhirbase/fhir.clj/blob/dab52ee/src/fhir/profiles.clj#L68
* https://github.com/fhirbase/fhir.clj/blob/dab52ee/src/fhir/utils.clj#L76

**Comment by niquola** [comment]
Thx Josh

but looks like fmap does not pass key into map-fn :( - https://github.com/clojure/algo.generic/blob/master/src/main/clojure/clojure/algo/generic/functor.clj#L33

**Comment by jmandel** [comment]
It's true, they don't. (I only took a quick look through your code and didn't see where we you were using the key itself.)
